### ISSUE TITLE
Support custom compression levels

### ISSUE THREAD

**Issue by richardgavel** [Inedo/Inedo.UPack#12]
We are creating universal packages which are quite large, potentially 1 GB. It would be nice if we could use the maximum possible compression when adding these files to a upack.

**Comment by apapadimoulis** [comment]
Thanks for the suggestion; we use the default, I believe.

How much of a difference would it make if you used maximum compression? It typically doesn't make a big difference in my experience

**Comment by richardgavel** [comment]
It's also not just about maximum compression, which does help. It's also about speed. There are instances where we put pre-compressed stuff inside a package. I'd like to be able to use Store (none) compression in those instances because compressing already compressed stuff doesn't shrink it any further, but does take time. And as these are outputs of our CI/CD process, even a minute saved per run matters.

**Comment by apapadimoulis** [comment]
Seems reasonable to me!
