### ISSUE TITLE
Add support for custom fields in PackageRegistry

### ISSUE THREAD

**Issue by wldevries** [Inedo/Inedo.UPack#17]
Allowing custom fields per installed package in the Package Registry would open up quite a lot of possibilities:

**Journaling**
You can either install a package and then register it in the Package Registry or the other way around. If anything happens in between you either end up with unallocated package contents on your disk or a package registry entry without any content installed. To remedy this a consumer of the UPack system could add an `_installstate` field with values such as `scheduled`, `configuring` and `installed`. This would enable validation of installed packages. Any packages with the state `scheduled` have not been or only partially been installed.

**Dependency Tracking**
Upack has a rather open-ended dependency system that would benefit from extra fields in the registry. We use meta packages with dependencies on a lot of other packages to install a whole batch of packages. It would be great if we could either add a `_dependencies` field with a list of other packages to the registry or an inverse `_dependents` field in combination. We will probably use the `installationReason` to record fixed options such as `dependency` and `manual` to resolve which package can be automatically uninstalled when one of these meta packages is uninstalled.

**Package Metadata**
It would be great to have a copy of the metadata of installed packages readily available in the registry. This would for instance help with dependency tracking. It would also help us having to duplicate metadata for packages and inside the package content.

Alternatively the registry could have a place to cache package metadata instead of whole upack files.

**Installed Content**
Having a list of installed files and a checksum of these files would allow validation of installed packages.

**Comment by gdivis** [comment]
This is now available as of [Inedo.UPack 1.0.7-pre0001](https://www.nuget.org/packages/Inedo.UPack/1.0.7-pre0001). If you'd like more changes, just comment here again and we can iterate on this before doing a stable 1.0.7 release.
