### ISSUE TITLE
Support for transparently adding x509 client certificate authentication

### ISSUE THREAD

**Issue by tknerr** [Inedo/Inedo.UPack#18]
Hi everybody,

we are about to use `upack` for uploading generic packages. However, depending on whether we are connecting from the internal or external network to our ProGet instance, we need to connect using an x509 client certificate.

I was hoping that usage of a client certificate could be transparently configured (e.g. via an environment variable or similar), however I could not find a standard way that .NET supports out-of-the-box, neither could I find support for that in https://github.com/Inedo/Inedo.UPack/blob/master/src/Inedo.UPack/Net/DefaultApiTransport.cs

Is there way to add client certificate authentication currently, that I might have overlooked?

If not, would you be open to add such functionality?

Cheers,
Torben

**Comment by apxltd** [comment]
In Windows, I think all this stuff is transparently handled by the Windows certificate manager? It's never been anything we have to worry about in our products, and I'm not sure how to do it in .NET either. 

I'm definitely open to adding it.... for us to code it is a challenge. It's pretty far from our expertise, so it'd take an unknown amount of resources to dev/test/etc., and there's very limited demand (you're first person to ask). 

But we'd definitely welcome a pull request! It's "probably not that hard", I'd hope. And I bet it could be done in a backwards-compatible way?

**Comment by jkuemerle** [comment]
Certificate based client authentication in .NET is much more than adding the clients public keys to the Windows certificate manager. I would also recommend not just client certificate authentication, but fully supporting mutual TLS authentication. That way you authenticate both the client and the server to each other.

.NET, especially .NET core does have mechanisms to support this. Good starting points for some example code are: 

https://medium.com/@therealjordanlee/securing-web-applications-with-mtls-asp-net-core-2-x-e93660b6b9ea 

https://blogs.msdn.microsoft.com/kaevans/2016/04/13/azure-web-app-client-certificate-authentication-with-asp-net-core-2/

https://www.codeproject.com/Articles/326574/An-Introduction-to-Mutual-SSL-Authentication

https://stackoverflow.com/questions/43213675/dotnetcore-mutual-certificate-authentication

Having had to work with, and secure mTLS endpoints, I definitely recommend having the work done by someone who is familiar with the intricacies of PKI and TLS authentication. There are a number of fairly unique challenges and troubleshooting can require some specialized use of proxy tooling.  

https://security.stackexchange.com/questions/62122/how-to-troubleshoot-client-certificate-related-errors-in-2-way-https

https://medium.com/sitewards/the-magic-of-tls-x509-and-mutual-authentication-explained-b2162dec4401

https://www.venafi.com/blog/back-server-it-time-require-mutual-tls-authentication

Also, Dominick Baier has a really good three part series that includes some good information about mTLS in .NET

https://leastprivilege.com/2020/01/15/oauth-2-0-the-long-road-to-proof-of-possession-access-tokens/

https://leastprivilege.com/2020/02/07/mutual-tls-and-proof-of-possession-access-tokens-part-1-setup/

https://leastprivilege.com/2020/02/12/mutual-tls-and-proof-of-possession-tokens-summary/

https://identityserver4.readthedocs.io/en/latest/topics/mtls.html

**Comment by apxltd** [comment]
Thanks @jkuemerle , very interesting. Seems a bit more involved, after all.

We'll keep an eye on this, and see if there's any demand for this sort of stuff in our products!

**Comment by tknerr** [comment]
Thanks @apxltd @jkuemerle for the insights. I don't have any capacities for contributing to this right now, but this might change in case it become more pressing for us to have that... let's keep it open as a "feature request" until then?

**Comment by apxltd** [comment]
From a management standpoint, I don't like keeping issues open (i.e. visible on a dashboard, somewhere) unless there's a plan to take action... even if that action is a concrete date that we will re-evaluate it. 

No such plan/action item exists now, so I'll close the ticket, but like you mentioned, things might change in the future, so we can find it again and open it right back up :)
