### ISSUE TITLE
Add simplified package installation logic from upack CLI

### ISSUE THREAD

**Issue by pfeigl** [Inedo/Inedo.UPack#26]
Hi,

I know - the title is a little generic - so sorry for that.
I'll try to explain our usecase and make clear what I actually mean.

While the upack format does actually define alot of good functionality for a generic packaging system, there are a few details left out (inentionally). One of those is dependency management.

This means, we do actually have to create our own tooling around the upack file format and to my current understanding there are two ways to do this:
* Use the CLI and than probably create the tooling in PowerShell
* Create the tooling completely in .NET and use this library

The native .NET tooling would be my favorite, however only the CLI takes care updating the repository and using cached packages if available. While I do fully understand, that I can just replicate all of this by leveraging the correct library methods, I'd love to have this functionality built into the library.

I'm pretty much referring to the code in https://github.com/Inedo/upack/blob/master/src/upack/Install.cs , specifically the cache handling 

https://github.com/Inedo/upack/blob/ed87a8abe9d6905daed10bcabe56104b3bc81cec/src/upack/Install.cs#L134 

and the update of the registry 

https://github.com/Inedo/upack/blob/ed87a8abe9d6905daed10bcabe56104b3bc81cec/src/upack/Install.cs#L112

This feels like code which should be part of the library and not the client.

Thanks for your feedback!
Philipp

(p.s. we are currently evaluating bringing our completely self-crafted dependency management based on Artifactory over to ProGet using upack, so you might see some more questions from me sson :-) )

**Comment by gdivis** [comment]
Hi- great feedback, thanks for this, and I agree completely. Since this is all already implemented in upack, it should be easy to get this in here pretty soon (hopefully this week- I'll keep you updated).

**Comment by gdivis** [comment]
Hi @pfeigl -  what do you think about the approach in the attached commit? It's not finished, but I wanted to get your feedback before we went any further with it.

Unrelated, but I'd also like to get synchronous versions of most of the async methods in for this version too.
