### ISSUE TITLE
UniversalPackage leaves file stream open when a corrupt file is passed in

### ISSUE THREAD

**Issue by wldevries** [Inedo/Inedo.UPack#28]
When using the constructor `UniversalPackage(string fileName)` on a corrupt zip file or a file that is not a zip file the constructor will crash and leave the file handle open.

**Steps to reproduce**
1. Create a corrupt `.upack` file
2. Execute the following code
```
try
{
    using (var upack = new UniversalPackage(packagePath))
    {
        return upack.GetFullMetadata();
    }
}
catch (InvalidDataException)
{
    while (true)
        File.Delete(packagePath);
}
```

**Expected result**
I would expect the failing constructor to clean up the file handle making it possible to delete the file on failure.

**Actual result**
File handle is not released for corrupt packages. (it may be released after a long time by the garbage collector, I'm not sure)

**Comment by gdivis** [comment]
Thanks! We'll get this fixed in v1.0.9.
