### ISSUE TITLE
UniversalPackageDependency is serialized with * for missing version

### ISSUE THREAD

**Issue by wldevries** [Inedo/Inedo.UPack#30]
The `UniversalPackageBuilder` uses the `*` character for dependencies with missing versions. The manifest specification is not clear on the matter, but the Universal Package Explorer tool notes that `*` does not follow semantic versioning.

### Steps to reproduce
Run the following code
```
var upackmeta = new UniversalPackageMetadata
{
    Name = "MyFirstPackage",
    Version = new UniversalPackageVersion(0, 0, 0)
};

upackmeta.Dependencies.Add(new UniversalPackageDependency("Group", "OtherPackage));
using var upack = new UniversalPackageBuilder(upackPath, upackmeta);
```

### Expected result
```
{
  "name": "MyFirstPackage",
  "version": "0.0.0",
  "dependencies": [
    "Group/OtherPackage"
  ]
}
```

### Actual result
```
{
  "name": "MyFirstPackage",
  "version": "0.0.0",
  "dependencies": [
    "Group/OtherPackage:*"
  ]
}
```

**Comment by gdivis** [comment]
Thanks! I've published v1.0.11 to NuGet with this fix.
