### ISSUE TITLE
Feature Request: Ability to Configure Timeout Settings in UniversalFeedClient

### ISSUE THREAD

**Issue by davepiar** [Inedo/Inedo.UPack#54]
Hello,

I am using the `UniversalFeedClient` from the UpackLib.NET library for handling universal packages via HTTP requests. I encountered an issue where the default timeout settings of the HTTP client are not suitable for my use case, particularly when uploading large packages or under slow network conditions.

Currently, there appears to be no straightforward method to configure the timeout settings of the HTTP client within the `UniversalFeedClient` class. This limitation can lead to timeouts during the upload of large .upack files or when the network is slow, impacting the robustness of operations dependent on this client.

### Request

Could it be possible to introduce a feature that allows users to configure the HTTP client's timeout settings when initializing an instance of `UniversalFeedClient`? This enhancement would be incredibly beneficial for adjusting the client to different network environments and specific application requirements.

**Comment by gdivis** [comment]
Good idea! It is technically possible to do this now by either subclassing the `DefaultApiTransport` class or setting the `HttpClientFactory` property on it, but it would be nice to have a less awkward way to configure the default timeout.

**Comment by davepiar** [comment]
Thanks for sharing this approach, we'll check it. Anyway, do you think this feature could be integrated in the UPack library in the near future?

**Comment by gdivis** [comment]
Absolutely. What do you think of the approach in the referenced commit? (see the client-timeout branch)

**Comment by davepiar** [comment]
Awesome! The approach looks great to me, thanks you.
